//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ZooManagementSystem.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ZOOMANAGEMENTSYSTEM_DIALOG  102
#define IDR_MAINFRAME                   128
#define IDD_KeeperDialog                130
#define IDD_FormApplyGodfather          132
#define IDD_ManagerDialog               134
#define IDD_ManageGodfathersDialog      136
#define IDD_ManageAnimalsDialog         138
#define IDD_GodfatherDialog             140
#define IDD_ManageEmployeesDialog       144
#define IDD_ConfirmExtend               146
#define IDD_VeterinarianDialog          148
#define IDD_FoodDialog                  150
#define IDD_MedicineDialog              152
#define IDD_AddAnimalDialog             154
#define IDD_Assign_Tasks                158
#define IDD_NewGodAnimal                160
#define IDC_Username                    1000
#define IDC_Password                    1001
#define IDC_BUTTONLogin                 1002
#define IDC_EDIT1                       1003
#define IDC_Information                 1004
#define IDC_AnimalName                  1004
#define IDC_EditName                    1004
#define IDC_New_AnimalName              1004
#define IDC_Search1                     1005
#define IDC_newemployeepassword         1005
#define IDC_Order_Quantity              1005
#define IDC_AnimalGender                1006
#define IDC_newemployeebirthdate        1006
#define IDC_Stock_Description2          1006
#define IDC_newemployeebirthday         1006
#define IDC_AnimalBirth                 1007
#define IDC_newemployeeemail            1007
#define IDC_New_AnimalOrigin            1007
#define IDC_AnimalOrigin                1008
#define IDC_newemployeebegincontract    1008
#define IDC_newemployeebegincontractday 1008
#define IDC_AnimalWild                  1009
#define IDC_newemployeeendcontract      1009
#define IDC_AnimalSpecie                1009
#define IDC_newemployeeendcontractday   1009
#define IDC_ZoneSearch                  1010
#define IDC_newemployeephone            1010
#define IDC_Search2                     1011
#define IDC_ResultsZone                 1012
#define IDC_ApplyGodfather              1013
#define IDC_AnimalList                  1014
#define IDC_ApplyNow                    1015
#define IDC_EditEmail                   1017
#define IDC_EditBirth                   1018
#define IDC_EditBirthYear               1018
#define IDC_Age                         1018
#define IDC_medicine_history_list       1018
#define IDC_food_history_list           1018
#define IDC_a_family                    1018
#define IDC_EditPassword                1019
#define IDC_COMBO1                      1020
#define IDC_ComboAnimal                 1020
#define IDC_COMBOPENDING                1020
#define IDC_COMBOEmployees              1020
#define IDC_stock_description_combo     1020
#define IDC_COMBO_Gender                1020
#define IDC_COMBO_task_type             1020
#define IDC_SelectNewGodAnimal          1020
#define IDC_ManageGodfathers            1021
#define IDC_COMBO_Species               1021
#define IDC_LISTPENDING                 1022
#define IDC_COMBO_Zone                  1022
#define IDC_RADIOACCEPT                 1023
#define IDC_RADIODECLINE                1024
#define IDC_BUTTONCONFIRM               1025
#define IDC_BUTTONMANAGEANIMALS         1028
#define IDC_EditBirthDay                1029
#define IDC_EditBirthMonth              1030
#define IDC_AddEmployee                 1030
#define IDC_GodAnimalImage              1031
#define IDC_EliminateEmployee           1031
#define IDC_ComboGodanimal              1031
#define IDC_ManageEmployees             1032
#define IDC_Adicionar                   1032
#define IDC_Name                        1034
#define IDC_Gender                      1035
#define IDC_newemployeename             1037
#define IDC_Origin                      1037
#define IDC_ADDEmployeeButton           1038
#define IDC_CommonName                  1038
#define IDC_Phylum                      1039
#define IDC_EmployeesList               1040
#define IDC_Class                       1040
#define IDC_EliminateEmployeeButton     1041
#define IDC_Order                       1041
#define IDC_OrderFoodButton             1041
#define IDC_ManagerRadio                1042
#define IDC_Suborder                    1042
#define IDC_KeeperRadio                 1043
#define IDC_Family                      1043
#define IDC_VeterinarianRadio           1044
#define IDC_Subfamily                   1044
#define IDC_ScientificName              1045
#define IDC_NewManagerType              1046
#define IDC_Conservation                1046
#define IDC_NewKeeperType               1047
#define IDC_Animal_Photo                1047
#define IDC_new_stock_unitvalue         1047
#define IDC_NewVeterinarianType         1048
#define IDC_StartDate                   1048
#define IDC_EndDate                     1049
#define IDC_New_item_order_button       1049
#define IDC_Fee                         1050
#define IDC_BUTTON_Extend               1052
#define IDC_BUTTON_Yes                  1054
#define IDC_BUTTON_Cancel               1055
#define IDC_NewEnd                      1057
#define IDC_HistoryRecords              1058
#define IDC_OrderButton                 1059
#define IDC_ADD_Animal_Button           1061
#define IDC_WildDate_Button             1062
#define IDC_EditWildYear                1066
#define IDC_EditWildMonth               1067
#define IDC_EditWildDay                 1068
#define IDC_animal_listbox              1070
#define IDC_New_Animal_Photo            1072
#define IDC_Task_to_add                 1074
#define IDC_AddTask_Button              1075
#define IDC_COMBO_keeper                1076
#define IDC_COMBO_zones                 1077
#define IDC_COMBO_tasks                 1078
#define IDC_AssignTask_Button           1079
#define IDC_EditTaskYear                1080
#define IDC_EditTaskMonth               1081
#define IDC_EditTaskDay                 1082
#define IDC_BUTTON1                     1083
#define IDC_Add_Assign_Tasks_Button     1083
#define IDC_ADD_Record                  1083
#define IDC_InsertToday                 1083
#define IDC_ConsumptionButton           1083
#define IDC_RegConsMed                  1083
#define IDC_BUTTON_NewGodAnimal         1083
#define IDC_ButtonSubmitRequest         1083
#define IDC_a_ID                        1084
#define IDC_a_gender                    1085
#define IDC_a_birth                     1086
#define IDC_a_age                       1087
#define IDC_a_origin                    1088
#define IDC_a_specie                    1089
#define IDC_a_phylum                    1091
#define IDC_a_class                     1092
#define IDC_a_order                     1093
#define IDC_a_suborder                  1094
#define IDC_a_subfamily                 1095
#define IDC_a_scientific                1096
#define IDC_a_conservation              1097
#define IDC_Type_Routine                1098
#define IDC_Type_Emergency              1099
#define IDC_new_description             1100
#define IDC_new_prescription            1101
#define IDC_new_year                    1102
#define IDC_new_month                   1103
#define IDC_new_day                     1104
#define IDC_insert_today                1105
#define IDC_tasks_today                 1106
#define IDC_tasks_history               1107
#define IDC_Result_Biome                1108
#define IDC_AnimalZone                  1109
#define IDC_ResponsibleFood             1110
#define IDC_ResponsibleMedicine         1111
#define IDC_ResponsibleNone             1112
#define IDC_birth_month                 1113
#define IDC_begin_month                 1114
#define IDC_end_month                   1115
#define IDC_birth_year                  1116
#define IDC_begin_year                  1117
#define IDC_end_year                    1118
#define IDC_CurrentStock                1119
#define IDC_food_consumption            1120
#define IDC_ConsumptionQuantity         1121
#define IDC_COMBO_Consumption           1122
#define IDC_AnimalConsumption           1123
#define IDC_CurrStockMedicine           1124
#define IDC_HistoryStockMed             1125
#define IDC_Combo_Consumption_med       1127
#define IDC_Consumed_Quant_med          1128
#define IDC_Consume_Animal_med          1129
#define IDC_OrderMedicineButton         1130
#define IDC_SelectedSpecie              1131
#define IDC_EDIT2                       1132
#define IDC_SelectedFee                 1132

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1133
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
